In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
celiac_df = pd.read_csv("celiac_disease_lab_data.csv")
celiac_df.iloc[-15:]

Age  Gender Diabetes Diabetes Type     Diarrhoea Abdominal  \
2191    6  Female      Yes        Type 1  inflammatory       yes   
2192    6    Male      Yes        Type 1        watery       yes   
2193   10    Male      Yes        Type 1        watery        no   
2194    3    Male      Yes        Type 1  inflammatory       yes   
2195    7    Male       no           NaN  inflammatory        no   
2196    9  Female       no           NaN        watery       yes   
2197   10  Female       no           NaN        watery        no   
2198    6    Male      Yes        Type 1  inflammatory       yes   
2199   10    Male      Yes        Type 1        fatty        yes   
2200    9  Female      Yes        Type 1  inflammatory       yes   
2201    3    Male      Yes        Type 1        fatty        yes   
2202   11  Female      Yes        Type 1        watery       yes   
2203   15    Male      Yes        Type 1        watery       yes   
2204    7  Female       no           NaN        fatty        yes   
2205   12  Female      Yes        Type 1  inflammatory       yes   

     Short_Stature Sticky_Stool Weight_loss   IgA   IgG   IgM          Marsh  \
2191           PSS           no         yes  1.00  11.5  2.00  marsh type 3a   
2192           PSS           no         yes  1.00  11.0  1.30           none   
2193      Variant           yes          no  2.30   7.0  2.10  marsh type 3b   
2194           PSS          yes         yes  1.00   9.0  1.40   marsh type 1   
2195           PSS          yes          no  1.00   9.4  1.60           none   
2196           PSS          yes          no  1.20   9.0  1.00           none   
2197           DSS           no          no  1.30   8.0  1.00           none   
2198           PSS          yes         yes  0.51  13.4  0.91   marsh type 2   
2199      Variant           yes         yes  1.80  13.0  0.80  marsh type 3b   
2200           PSS          yes         yes  1.30   9.0  1.10   marsh type 1   
2201           PSS          yes          no  1.10   7.0  0.60   marsh type 2   
2202           PSS          yes          no  1.40  12.0  1.10           none   
2203           PSS          yes          no  0.34  10.0  0.60   marsh type 0   
2204           DSS          yes         yes  2.10   8.5  2.10           none   
2205      Variant           yes         yes  1.90  11.1  1.10           none   

        cd_type Disease_Diagnose  
2191     silent              yes  
2192       none               no  
2193   atypical              yes  
2194  potential              yes  
2195       none               no  
2196       none               no  
2197       none               no  
2198    typical              yes  
2199   atypical              yes  
2200     latent               no  
2201    typical              yes  
2202       none               no  
2203  potential              yes  
2204       none               no  
2205       none               no

In [3]:
celiac_df['Diarrhoea'].value_counts()

Diarrhoea
fatty           773
watery          723
inflammatory    710
Name: count, dtype: int64

In [4]:
celiac_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2206 entries, 0 to 2205
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Age               2206 non-null   int64  
 1   Gender            2206 non-null   object 
 2   Diabetes          2206 non-null   object 
 3   Diabetes Type     1788 non-null   object 
 4   Diarrhoea         2206 non-null   object 
 5   Abdominal         2206 non-null   object 
 6   Short_Stature     2206 non-null   object 
 7   Sticky_Stool      2206 non-null   object 
 8   Weight_loss       2206 non-null   object 
 9   IgA               2206 non-null   float64
 10  IgG               2206 non-null   float64
 11  IgM               2206 non-null   float64
 12  Marsh             2206 non-null   object 
 13  cd_type           2206 non-null   object 
 14  Disease_Diagnose  2206 non-null   object 
dtypes: float64(3), int64(1), object(11)
memory usage: 258.6+ KB


In [5]:
celiac_df.describe()

Age          IgA          IgG          IgM
count  2206.000000  2206.000000  2206.000000  2206.000000
mean     12.768812     1.427384    10.052901     1.236963
std       7.434250     1.110042     2.047683     0.447216
min       1.000000     0.340000     5.000000     0.500000
25%       8.000000     1.000000     8.700000     0.980000
50%      10.000000     1.100000    10.000000     1.100000
75%      15.000000     1.800000    12.000000     1.500000
max      35.000000     9.000000    15.300000     2.700000

In [6]:
celiac_df = celiac_df.drop(['Diabetes Type', 'Marsh', 'cd_type', 'Gender'], axis=1)
celiac_df = celiac_df.dropna()
celiac_df

Age Diabetes     Diarrhoea Abdominal Short_Stature Sticky_Stool  \
0      10      Yes  inflammatory       yes           PSS           no   
1       9      Yes        fatty        yes           PSS           no   
2       8      Yes        watery       yes      Variant           yes   
3      10      Yes        watery       yes           PSS           no   
4       9      Yes        fatty        yes           PSS           no   
...   ...      ...           ...       ...           ...          ...   
2201    3      Yes        fatty        yes           PSS          yes   
2202   11      Yes        watery       yes           PSS          yes   
2203   15      Yes        watery       yes           PSS          yes   
2204    7       no        fatty        yes           DSS          yes   
2205   12      Yes  inflammatory       yes      Variant           yes   

     Weight_loss   IgA   IgG   IgM Disease_Diagnose  
0             no  1.30  10.0  1.00              yes  
1             no  1.50  12.5  1.30              yes  
2            yes  0.40   8.0  0.50              yes  
3             no  0.98   9.0  0.66              yes  
4             no  1.00  10.5  1.10              yes  
...          ...   ...   ...   ...              ...  
2201          no  1.10   7.0  0.60              yes  
2202          no  1.40  12.0  1.10               no  
2203          no  0.34  10.0  0.60              yes  
2204         yes  2.10   8.5  2.10               no  
2205         yes  1.90  11.1  1.10               no  

[2206 rows x 11 columns]

In [7]:
X = celiac_df.drop(['Disease_Diagnose'], axis=1)
y = celiac_df['Disease_Diagnose']

In [8]:
numerical = X.drop(['Diabetes', 'Diarrhoea', 'Abdominal', 'Short_Stature', 'Sticky_Stool', 'Weight_loss'], axis = 1)
numerical.head()

Age   IgA   IgG   IgM
0   10  1.30  10.0  1.00
1    9  1.50  12.5  1.30
2    8  0.40   8.0  0.50
3   10  0.98   9.0  0.66
4    9  1.00  10.5  1.10

In [9]:
categorical = X.filter(['Gender', 'Diabetes','Diarrhoea', 'Abdominal', 'Short_Stature', 'Sticky_Stool', 'Weight_loss'])
categorical.head()

Diabetes     Diarrhoea Abdominal Short_Stature Sticky_Stool Weight_loss
0      Yes  inflammatory       yes           PSS           no          no
1      Yes        fatty        yes           PSS           no          no
2      Yes        watery       yes      Variant           yes         yes
3      Yes        watery       yes           PSS           no          no
4      Yes        fatty        yes           PSS           no          no

In [10]:
cat_numerical = pd.get_dummies(categorical,drop_first=True)
cat_numerical.head()

Diabetes_no  Diarrhoea_inflammatory  Diarrhoea_watery  Abdominal_yes  \
0        False                    True             False           True   
1        False                   False             False           True   
2        False                   False              True           True   
3        False                   False              True           True   
4        False                   False             False           True   

   Short_Stature_PSS  Short_Stature_Variant   Sticky_Stool_yes  \
0               True                   False             False   
1               True                   False             False   
2              False                    True              True   
3               True                   False             False   
4               True                   False             False   

   Weight_loss_yes  
0            False  
1            False  
2             True  
3            False  
4            False

In [11]:
X = pd.concat([numerical, cat_numerical], axis = 1)
X.head()

Age   IgA   IgG   IgM  Diabetes_no  Diarrhoea_inflammatory  \
0   10  1.30  10.0  1.00        False                    True   
1    9  1.50  12.5  1.30        False                   False   
2    8  0.40   8.0  0.50        False                   False   
3   10  0.98   9.0  0.66        False                   False   
4    9  1.00  10.5  1.10        False                   False   

   Diarrhoea_watery  Abdominal_yes  Short_Stature_PSS  Short_Stature_Variant   \
0             False           True               True                   False   
1             False           True               True                   False   
2              True           True              False                    True   
3              True           True               True                   False   
4             False           True               True                   False   

   Sticky_Stool_yes  Weight_loss_yes  
0             False            False  
1             False            False  
2              True             True  
3             False            False  
4             False            False

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
test_size=0.20, random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform (X_test)

In [14]:
from sklearn import svm

# Initialize the Support Vector Classifier
svm_clf = svm.SVC(probability=True)

# Fit the classifier to the training data
classifier = svm_clf.fit(X_train, y_train)

# Predict on the test data
y_pred = classifier.predict(X_test)

# Scaling a single record
single_record = sc.transform(X.iloc[900].to_frame().T)

# Making predictions on the single record
predicted_class = classifier.predict(single_record)

# Print the predicted bankrupt class outcome
print("Index [900] Single Value Prediction Comparison:\n")
print(f"Actual Class: 1 | Predicted Class: {predicted_class[0]}\n\n")

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Print the confusion matrix
print("Confusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

print("\n")

# Print the classification report
print(classification_report(y_test, y_pred))

# Print the accuracy score
print("Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.model_selection import cross_val_score

# Print the cross-validation score
print("\n\nAccuracy K-Fold Cross Val:\n")
print(cross_val_score(classifier, X, y, cv=5, scoring="accuracy"))

Index [900] Single Value Prediction Comparison:

Actual Class: 1 | Predicted Class: yes


Confusion Matrix:

[[ 65  11]
 [  0 366]]


              precision    recall  f1-score   support

          no       1.00      0.86      0.92        76
         yes       0.97      1.00      0.99       366

    accuracy                           0.98       442
   macro avg       0.99      0.93      0.95       442
weighted avg       0.98      0.98      0.97       442

Accuracy: 0.9751131221719457


Accuracy K-Fold Cross Val:

[0.95701357 0.92743764 0.97052154 0.93650794 0.91836735]


In [15]:
import pickle
filename = 'celiac_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [16]:
load_model = pickle.load(open(filename, 'rb'))

In [20]:
load_model.predict([[10, 1.30, 10.0, 1.00, False, True, False, True, True, False,	False, False]])


array(['yes'], dtype=object)

In [21]:
load_model.predict_proba([[10, 1.30, 10.0, 1.00, False, True, False, True, True, False,	False, False]])

array([[0.30941666, 0.69058334]])